### ISSUE TITLE
build_loader function missing

### ISSUE THREAD

**Issue by arezaz** [LeapLabTHU/DAT#1]
https://github.com/LeapLabTHU/DAT/blob/4bb699e2122d7b4eb52e7080f97ea054f34b65b0/main.py#L27

I think ./data is missing. Is build_loader function supposed to be:
https://github.com/microsoft/Swin-Transformer/blob/5d2aede42b4b12cb0e7a2448b58820aeda604426/data/build.py#L38

**Comment by Vladimir2506** [comment]
Thanks for pointing out this bug, I slipped up with an additional 'data' in the .gitignore file. Please refer to 001ed3d.
