### ISSUE TITLE
what does -1 mean in strides and groups variable

### ISSUE THREAD

**Issue by Hua-YS** [LeapLabTHU/DAT#14]
Hi, thanks for your nice work. I'm very confused with the negative values (-1) in strides and groups. For example, strides=[-1,-1,1,1] or groups=[-1.-1.3,6]. This also triggers errors when creating weight tensors due to that negative dimensions are not allowed in tensors: 

RuntimeError: Trying to create tensor with negative dimension -96: [-96, 1, 9, 9]

It would be appreciated if you can explain what does -1 mean here.

Thanks in advance!

**Comment by Vladimir2506** [comment]
This **stride** controls the stride of the offset generation module and only takes effects at the last two stages. I set it to a negative number as default for debugging since an error will be triggered if it is not set properly.
