### ISSUE TITLE
The computational cost of deformabel attention

### ISSUE THREAD

**Issue by linjing7** [LeapLabTHU/DAT#16]
Hi, thanks for your excellent work.
I notice that the number of the sampled keys/values is the same as the querys. Therefore, the computational cost of deformable attention is the same as global attention, is it right? So I'm curious why don't you use a global self-attention at the last two stages?

**Comment by Vladimir2506** [comment]
Thanks for your question. It's right. Please refer to Table 6 the ablation study section in the paper. In fact, the settings in the paper may not be optimal, and there might be some better results as we conduct more detailed investigations these days.

**Comment by linjing7** [comment]
Okay, thank you very much.
