### ISSUE TITLE
Exporting of object detection & segmentation code

### ISSUE THREAD

**Issue by Filipwansen** [LeapLabTHU/DAT#2]
Hello
How are you?
Thanks for contributing to this project.
When can we expect to get the object detection & segmentation code?

**Comment by stayhungry1** [comment]
Really looking forward to the code for classification, object detection and segmentation!

**Comment by yuanbianGit** [comment]
Really looking forward to the code for classification! Thanks!

**Comment by Sairam13001** [comment]
Thank you for this awesome work! 
Could you kindly let me know a probable time when the object detection code might be released?

**Comment by Vladimir2506** [comment]
I have been working on polishing the codes, and am about to commit them in a few weeks.

**Comment by tdchua** [comment]
Hi there! Has there been an update regarding this? :D

**Comment by Vladimir2506** [comment]
Hello @tdchua @Filipwansen @Sairam13001 @stayhungry1 @yuanbianGit,

Sorry for being so late. The code repos of detection and segmentation are updated along with the newer extended version of DAT. Please check them out and feel free to raise issues if you encounter any problems.
