### ISSUE TITLE
About Low Accuracy

### ISSUE THREAD

**Issue by z1zzzz1** [LeapLabTHU/DAT#20]
Hi, thanks for your excellent work.But when I use your DAT model and pre trained weights for image segmentation tasks, the effect is not ideal. I do this: take out the features of each layer and then recover the image size through simple deconvolution up sampling and skip connection operations. The code is as follows:
![image](https://user-images.githubusercontent.com/102965475/196589164-fe368b46-4c8a-405f-aa7e-a579aa92527c.png)

If possible, please tell me where the error is. I hope you can publish the segmentation model as soon as possible and look forward to your reply. Thank you

**Comment by Vladimir2506** [comment]
Hello @z1zzzz1,

The deconvolution is a rather weak operator as the decoder in segmentation models. In fact, it is better to use some powerful decoder heads for segmentation tasks. The [detection](https://github.com/LeapLabTHU/DAT-Detection) and [segmentation](https://github.com/LeapLabTHU/DAT-Segmentation) codes are released, along with the extended version of the paper DAT++. We welcome you to check them out. Please feel free to let us know if you encounter any problem.
