### ISSUE TITLE
evaluate.sh: line 6: path-to-imagenet: No such file or directory

### ISSUE THREAD

**Issue by hygxy** [LeapLabTHU/DAT#25]
when running ```bash evaluate.sh 1 configs/dat_tiny.yaml ./dat_tiny_in1k_224.pth```, i get the following error:
```
evaluate.sh: line 6: path-to-imagenet: No such file or directory
```

**Comment by Vladimir2506** [comment]
Hello @hygxy,

This `path-to-imagenet` is to modified to your own path on your local machine where ImageNet-1K is stored.
