### ISSUE TITLE
Controlling the number of keys per query

### ISSUE THREAD

**Issue by tdchua** [LeapLabTHU/DAT#26]
In the appendix of DAT vs D-DETR, you mentioned changing the number of keys in Stage 3 and Stage 4. I was wondering where in the code, can you change for that? Thank you.

**Comment by Vladimir2506** [comment]
Hello @tdchua,

This part of the code has not been published yet, however the number of keys in DAT can be controlled by the kernel size, dilation rate, and stride of the DWC in `offset_conv` module. And You can easily port the `MSDeformAttn` in D-DETR or just implement a `F.grid_sample` version.
