### ISSUE TITLE
Different depthwise convolution kernel sizes?

### ISSUE THREAD

**Issue by xskxzr** [LeapLabTHU/DAT#5]
In your paper, I see you use a depthwise convolution with kernel size 5 to generate offsets, but in the code [you use different kernel sizes for different input sizes](https://github.com/LeapLabTHU/DAT/blob/main/models/dat_blocks.py#L153). Am I missing something?

**Comment by Vladimir2506** [comment]
In our experiments, k=5 in stage 3, k=3 in stage 4 work well.
