### ISSUE TITLE
Pretrain Model

### ISSUE THREAD

**Issue by xxtars** [LeapLabTHU/DAT#6]
Would you release the pretrain model of DAT.

Thanks.

**Comment by lxtGH** [comment]
Would you release the pretrain model of DAT.

Thanks.

**Comment by Li-Qingyun** [comment]
Would you release the pretrain model of DAT.

Thanks.

**Comment by lprintf** [comment]
It's so appealing, I can't wait to see its pretrained model.

Thanks！

**Comment by Vladimir2506** [comment]
Thanks for your concerns, the pretrained weights are committed.
