### ISSUE TITLE
固定输入图片尺寸

### ISSUE THREAD

**Issue by houjie8888** [LeapLabTHU/DAT#7]
你好，非常引人注目的工作，我注意到position embeddings采用relative方法的话，需要固定测试图片的大小，而采用dwconv方法可能会占用非常大的显存，不知道作者有没有处理动态输入图像尺寸的方法。

**Comment by Vladimir2506** [comment]
You can consider interpolating the relative position embeddings according to the resolution of the input image, as mentioned in the original paper.
